/* ───────────────────────────────────────────
   Service area data - all cities within a 3.5-hour
   drive of Roseville, CA, organized by region for
   local SEO coverage. Shared by the on-page service
   section and the footer city directory.
   ─────────────────────────────────────────── */

export interface City {
  name: string;
  drive: string;
}

export interface Region {
  label: string;
  id: string;
  cities: City[];
}

// City display name → slug for cities that have a dedicated
// /locations/ca/[slug] landing page. Keep in sync with cities.ts.
export const CITY_PAGE_SLUGS: Record<string, string> = {
  Sacramento: "sacramento",
  Folsom: "folsom",
  Rocklin: "rocklin",
  "Granite Bay": "granite-bay",
  Lincoln: "lincoln",
  "Elk Grove": "elk-grove",
  "El Dorado Hills": "el-dorado-hills",
  Auburn: "auburn",
  "Citrus Heights": "citrus-heights",
  "Rancho Cordova": "rancho-cordova",
  Vacaville: "vacaville",
  Vallejo: "vallejo",
  Fairfield: "fairfield",
  Oroville: "oroville",
};

export const regions: Region[] = [
  {
    label: "Sacramento Metro",
    id: "sacramento",
    cities: [
      { name: "Roseville", drive: "Main Office" },
      { name: "Sacramento", drive: "20 min" },
      { name: "Folsom", drive: "20 min" },
      { name: "Rocklin", drive: "8 min" },
      { name: "Lincoln", drive: "15 min" },
      { name: "Granite Bay", drive: "10 min" },
      { name: "Citrus Heights", drive: "10 min" },
      { name: "Orangevale", drive: "12 min" },
      { name: "Fair Oaks", drive: "15 min" },
      { name: "Carmichael", drive: "15 min" },
      { name: "Rancho Cordova", drive: "20 min" },
      { name: "Elk Grove", drive: "35 min" },
      { name: "North Highlands", drive: "12 min" },
      { name: "Antelope", drive: "10 min" },
      { name: "Arden-Arcade", drive: "15 min" },
      { name: "West Sacramento", drive: "25 min" },
      { name: "El Dorado Hills", drive: "20 min" },
      { name: "Cameron Park", drive: "25 min" },
      { name: "Loomis", drive: "12 min" },
      { name: "Auburn", drive: "25 min" },
      { name: "Woodland", drive: "25 min" },
      { name: "Davis", drive: "30 min" },
      { name: "Placerville", drive: "40 min" },
      { name: "Galt", drive: "40 min" },
    ],
  },
  {
    label: "Yuba-Sutter & Butte County",
    id: "yuba-butte",
    cities: [
      { name: "Yuba City", drive: "40 min" },
      { name: "Marysville", drive: "35 min" },
      { name: "Wheatland", drive: "25 min" },
      { name: "Live Oak", drive: "50 min" },
      { name: "Gridley", drive: "55 min" },
      { name: "Oroville", drive: "1 hr 10 min" },
      { name: "Chico", drive: "1 hr 30 min" },
      { name: "Paradise", drive: "1 hr 35 min" },
      { name: "Grass Valley", drive: "50 min" },
      { name: "Nevada City", drive: "55 min" },
      { name: "Colfax", drive: "35 min" },
    ],
  },
  {
    label: "North State & Shasta County",
    id: "north-state",
    cities: [
      { name: "Redding", drive: "2 hr 40 min" },
      { name: "Anderson", drive: "2 hr 30 min" },
      { name: "Shasta Lake", drive: "2 hr 45 min" },
      { name: "Red Bluff", drive: "2 hr 10 min" },
      { name: "Corning", drive: "2 hr" },
      { name: "Willows", drive: "1 hr 40 min" },
      { name: "Orland", drive: "1 hr 50 min" },
      { name: "Colusa", drive: "1 hr 10 min" },
      { name: "Williams", drive: "1 hr" },
    ],
  },
  {
    label: "Lake Tahoe & Sierra",
    id: "tahoe-sierra",
    cities: [
      { name: "Truckee", drive: "1 hr 30 min" },
      { name: "Tahoe City", drive: "1 hr 40 min" },
      { name: "Kings Beach", drive: "1 hr 45 min" },
      { name: "South Lake Tahoe", drive: "2 hr 10 min" },
      { name: "Incline Village, NV", drive: "1 hr 50 min" },
      { name: "Jackson", drive: "1 hr" },
      { name: "Sutter Creek", drive: "1 hr" },
      { name: "Angels Camp", drive: "1 hr 30 min" },
      { name: "Sonora", drive: "1 hr 50 min" },
    ],
  },
  {
    label: "Reno & Northern Nevada",
    id: "reno-nevada",
    cities: [
      { name: "Reno, NV", drive: "2 hr 10 min" },
      { name: "Sparks, NV", drive: "2 hr 15 min" },
      { name: "Carson City, NV", drive: "2 hr 30 min" },
      { name: "Fernley, NV", drive: "2 hr 45 min" },
      { name: "Dayton, NV", drive: "2 hr 40 min" },
      { name: "Minden, NV", drive: "2 hr 45 min" },
      { name: "Gardnerville, NV", drive: "2 hr 50 min" },
      { name: "Fallon, NV", drive: "3 hr 10 min" },
      { name: "Sun Valley, NV", drive: "2 hr 20 min" },
    ],
  },
  {
    label: "San Francisco & Peninsula",
    id: "sf-peninsula",
    cities: [
      { name: "San Francisco", drive: "1 hr 45 min" },
      { name: "Daly City", drive: "1 hr 50 min" },
      { name: "South San Francisco", drive: "1 hr 50 min" },
      { name: "San Bruno", drive: "1 hr 55 min" },
      { name: "Millbrae", drive: "1 hr 55 min" },
      { name: "Burlingame", drive: "2 hr" },
      { name: "San Mateo", drive: "2 hr" },
      { name: "Foster City", drive: "2 hr" },
      { name: "Redwood City", drive: "2 hr 10 min" },
      { name: "Menlo Park", drive: "2 hr 10 min" },
      { name: "Pacifica", drive: "2 hr" },
      { name: "Half Moon Bay", drive: "2 hr 15 min" },
    ],
  },
  {
    label: "East Bay & Contra Costa",
    id: "east-bay",
    cities: [
      { name: "Oakland", drive: "1 hr 30 min" },
      { name: "Berkeley", drive: "1 hr 25 min" },
      { name: "Concord", drive: "1 hr 15 min" },
      { name: "Walnut Creek", drive: "1 hr 20 min" },
      { name: "Richmond", drive: "1 hr 15 min" },
      { name: "Antioch", drive: "1 hr 10 min" },
      { name: "Pittsburg", drive: "1 hr 15 min" },
      { name: "Brentwood", drive: "1 hr 10 min" },
      { name: "San Ramon", drive: "1 hr 30 min" },
      { name: "Danville", drive: "1 hr 25 min" },
      { name: "Pleasanton", drive: "1 hr 35 min" },
      { name: "Livermore", drive: "1 hr 30 min" },
      { name: "Dublin", drive: "1 hr 30 min" },
      { name: "Hayward", drive: "1 hr 40 min" },
      { name: "Fremont", drive: "1 hr 50 min" },
      { name: "Union City", drive: "1 hr 45 min" },
      { name: "Newark", drive: "1 hr 50 min" },
      { name: "San Leandro", drive: "1 hr 35 min" },
      { name: "Vallejo", drive: "1 hr 10 min" },
      { name: "Benicia", drive: "1 hr 10 min" },
      { name: "Martinez", drive: "1 hr 10 min" },
      { name: "Hercules", drive: "1 hr 10 min" },
      { name: "Lafayette", drive: "1 hr 20 min" },
    ],
  },
  {
    label: "South Bay & Silicon Valley",
    id: "south-bay",
    cities: [
      { name: "San Jose", drive: "2 hr 20 min" },
      { name: "Santa Clara", drive: "2 hr 20 min" },
      { name: "Sunnyvale", drive: "2 hr 15 min" },
      { name: "Mountain View", drive: "2 hr 15 min" },
      { name: "Palo Alto", drive: "2 hr 10 min" },
      { name: "Cupertino", drive: "2 hr 20 min" },
      { name: "Campbell", drive: "2 hr 25 min" },
      { name: "Los Gatos", drive: "2 hr 30 min" },
      { name: "Saratoga", drive: "2 hr 30 min" },
      { name: "Milpitas", drive: "2 hr" },
      { name: "Los Altos", drive: "2 hr 15 min" },
      { name: "Morgan Hill", drive: "2 hr 40 min" },
      { name: "Gilroy", drive: "2 hr 50 min" },
    ],
  },
  {
    label: "Napa, Sonoma & North Bay",
    id: "north-bay",
    cities: [
      { name: "Napa", drive: "1 hr 10 min" },
      { name: "American Canyon", drive: "1 hr 10 min" },
      { name: "St. Helena", drive: "1 hr 25 min" },
      { name: "Sonoma", drive: "1 hr 20 min" },
      { name: "Petaluma", drive: "1 hr 30 min" },
      { name: "Santa Rosa", drive: "1 hr 40 min" },
      { name: "Rohnert Park", drive: "1 hr 35 min" },
      { name: "Windsor", drive: "1 hr 50 min" },
      { name: "Healdsburg", drive: "1 hr 55 min" },
      { name: "Sebastopol", drive: "1 hr 50 min" },
      { name: "Cloverdale", drive: "2 hr 10 min" },
      { name: "Novato", drive: "1 hr 25 min" },
      { name: "San Rafael", drive: "1 hr 35 min" },
      { name: "Mill Valley", drive: "1 hr 45 min" },
      { name: "Sausalito", drive: "1 hr 45 min" },
      { name: "Tiburon", drive: "1 hr 45 min" },
      { name: "Ukiah", drive: "2 hr 30 min" },
      { name: "Clearlake", drive: "2 hr 10 min" },
      { name: "Lakeport", drive: "2 hr 15 min" },
    ],
  },
  {
    label: "Solano & Yolo County",
    id: "solano-yolo",
    cities: [
      { name: "Vacaville", drive: "50 min" },
      { name: "Fairfield", drive: "55 min" },
      { name: "Suisun City", drive: "55 min" },
      { name: "Dixon", drive: "35 min" },
    ],
  },
  {
    label: "San Joaquin Valley",
    id: "san-joaquin",
    cities: [
      { name: "Stockton", drive: "1 hr 10 min" },
      { name: "Lodi", drive: "50 min" },
      { name: "Tracy", drive: "1 hr 20 min" },
      { name: "Manteca", drive: "1 hr 15 min" },
      { name: "Lathrop", drive: "1 hr 15 min" },
      { name: "Ripon", drive: "1 hr 20 min" },
    ],
  },
  {
    label: "Central Valley South",
    id: "central-valley",
    cities: [
      { name: "Modesto", drive: "1 hr 30 min" },
      { name: "Turlock", drive: "1 hr 50 min" },
      { name: "Ceres", drive: "1 hr 40 min" },
      { name: "Oakdale", drive: "1 hr 35 min" },
      { name: "Riverbank", drive: "1 hr 30 min" },
      { name: "Patterson", drive: "1 hr 45 min" },
      { name: "Merced", drive: "2 hr 10 min" },
      { name: "Atwater", drive: "2 hr 5 min" },
      { name: "Los Banos", drive: "2 hr 15 min" },
      { name: "Madera", drive: "2 hr 30 min" },
      { name: "Fresno", drive: "2 hr 50 min" },
      { name: "Clovis", drive: "2 hr 55 min" },
      { name: "Sanger", drive: "3 hr" },
      { name: "Selma", drive: "3 hr 10 min" },
      { name: "Dinuba", drive: "3 hr 20 min" },
      { name: "Hollister", drive: "2 hr 50 min" },
      { name: "Santa Cruz", drive: "3 hr 10 min" },
      { name: "Watsonville", drive: "3 hr 20 min" },
    ],
  },
];

export const totalCities = regions.reduce((acc, r) => acc + r.cities.length, 0);
